### ISSUE TITLE
WCF new website

### ISSUE THREAD

**Issue by Steve-Cook** [capital-chaplains/workplace.chaplaincy.foundation#1]
Matthew - can you please establish a new website with the following parameters:

Domain names:  workplacechaplaincyfoundaiton.org. and workchapfound.org and wcfoundation.org.
(wcfoundation.org would be the main domain name, if we can get it.)

Logo:  I will email this to you.

Copy:  
Purpose - This corporation is formed exclusively for charitable and educational purposes as articulated in  section 501(c)(3) of the Internal Revenue Code of 1986.  The specific purpose of this corporation is to: 
- Develop a workplace chaplaincy training and certification program  
- Facilitate workplace chaplaincy research and internships  
- Provide local, state, and national workplace chaplaincy forums  
- Provide international workplace chaplaincy initiatives and consulting 
- Provide start-up funds for organizations and municipalities to 
    experience a workplace-based Chaplain Assistance Program (CAP)

Workplace Chaplaincy Foundation, Inc.
7228 Elmwood Ave.
Middleton, WI 53562

Contact: Steve Cook, President, 608-217-7261, Steve@CapChaps.Org

**Comment by matt-cook** [comment]
You can also register `.foundation` domain names now (instead of just .com/.org/etc), if you're interested. a bit pricier though $35/year each:https://www.name.com/domain/search-3-9/?keyword=chaplaincy.foundation

So you could get https://chaplaincy.foundation (which would include the option of https://workplace.chaplaincy.foundation, https://www.chaplaincy.foundation) or https://www.workplacechaplaincy.foundation as your primary domain if you'd like.

Pakou and I just registered `cook.company`

**Comment by matt-cook** [comment]
Your new site has been created: https://workplace.chaplaincy.foundation/
